### ISSUE TITLE
`doc_url` appears broken?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/dask_groupby-feedstock#1]
When trying to load the `doc_url` in the recipe:

https://github.com/conda-forge/dask_groupby-feedstock/blob/f961c5c2c89aaa4b65e011890dcd9bf7b9e339e6/recipe/meta.yaml#L45

Got the following:

<img width="1792" alt="Screen Shot 2021-11-11 at 12 15 30 PM" src="https://user-images.githubusercontent.com/3019665/141362989-dd8cfc8a-7849-4a55-8027-f08279ab54e0.png">

Not sure if that is expected or if there is a typo somewhere

**Comment by dcherian** [comment]
Thanks, that URL was aspirational, I haven't gotten around to the docs yet unfortunately.

**Comment by jakirkham** [comment]
Ah ok. No worries 🙂

Edit: Would it make sense to drop it for now?

**Comment by dopplershift** [comment]
Well the package is being renamed, so I think that obviates this.

**Comment by jakirkham** [comment]
Oh I see ( https://github.com/conda-forge/staged-recipes/pull/16969 )
